lambdas:
  custom_policies:
    describe-vpcs:
      action:
        - ec2:DescribeVpcs
    describe-subnets:
      action:
        - ec2:DescribeSubnets
  roles:
    default:
      policies_inline:
        - cloudwatch-logs
        - describe-vpcs
        - describe-subnets
  functions:
    cfhlmacros:
      role: default
      code: src/macros
      runtime: python3.6
      timeout: 60
      handler: index.lambda_handler
